# Generated by Django 5.1.7 on 2025-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='airlines/'),
        ),
    ]
