# Generated by Django 5.2 on 2025-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_railwaycompany_trainticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'verbose_name': 'Авиакомпания', 'verbose_name_plural': 'Авиакомпании'},
        ),
        migrations.AlterModelOptions(
            name='railwaycompany',
            options={'verbose_name': 'Ж/Д компания', 'verbose_name_plural': 'Ж/Д компании'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Горячий авиабилет', 'verbose_name_plural': 'Горячие авиабилеты'},
        ),
        migrations.AlterModelOptions(
            name='trainticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Горячий Ж/Д билет', 'verbose_name_plural': 'Горячие Ж/Д билеты'},
        ),
        migrations.AlterField(
            model_name='airline',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='airlines/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='railwaycompany',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='railwaycompany',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='railways/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='railwaycompany',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='airlines',
            field=models.ManyToManyField(to='api.airline', verbose_name='Авиакомпании'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='from_city',
            field=models.CharField(max_length=100, verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='to_city',
            field=models.CharField(max_length=100, verbose_name='Город прибытия'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transfers',
            field=models.CharField(max_length=100, verbose_name='Пересадки'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='arrival_time',
            field=models.TimeField(verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='companies',
            field=models.ManyToManyField(to='api.railwaycompany', verbose_name='Ж/Д компании'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='departure_time',
            field=models.TimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='from_city',
            field=models.CharField(max_length=100, verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='ticket_type',
            field=models.CharField(max_length=50, verbose_name='Тип билета'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='to_city',
            field=models.CharField(max_length=100, verbose_name='Город прибытия'),
        ),
    ]
