# Generated by Django 5.2 on 2025-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_airline_options_alter_railwaycompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Актуальная цена'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Время в пути'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Актуальная цена'),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Время в пути'),
        ),
    ]
