# Generated by Django 5.2 on 2025-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ticket_current_price_alter_ticket_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Фото тура')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Например: 4.8', max_digits=3, verbose_name='Оценка')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='Название отеля')),
                ('food_included', models.BooleanField(default=False, verbose_name='Питание включено')),
                ('pets_allowed', models.BooleanField(default=False, verbose_name='Можно с животными')),
                ('nights_count', models.PositiveIntegerField(verbose_name='Количество ночей')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Популярный тур',
                'verbose_name_plural': 'Популярные туры',
                'ordering': ['-created_at'],
            },
        ),
    ]
