# Generated by Django 5.2 on 2025-04-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_populartour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populartour',
            name='nights_count',
        ),
    ]
