# Generated by Django 5.2 on 2025-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_populartour_nights_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populartour',
            name='image',
            field=models.FileField(help_text='Поддерживаются форматы JPG, PNG, GIF, AVIF', upload_to='tours/', verbose_name='Фото тура'),
        ),
    ]
