# Generated by Django 5.2 on 2025-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_populartour_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название локации')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('image', models.FileField(help_text='Поддерживаются форматы JPG, PNG, AVIF', upload_to='travel_ideas/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Идея для поездки',
                'verbose_name_plural': 'Идеи для поездок',
                'ordering': ['-created_at'],
            },
        ),
    ]
