# Generated by Django 5.2 on 2025-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_railwayticket_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtrainticket',
            name='train_type',
            field=models.CharField(blank=True, help_text='Например: 026Г (двухэтажный состав)', max_length=100, null=True, verbose_name='Тип поезда'),
        ),
    ]
