# Generated by Django 5.2 on 2025-04-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchairticket',
            name='night_transfer',
            field=models.BooleanField(default=False, verbose_name='Ночная пересадка'),
        ),
        migrations.AddField(
            model_name='searchairticket',
            name='refundable',
            field=models.BooleanField(default=False, verbose_name='Возвратный билет'),
        ),
        migrations.AddField(
            model_name='searchairticket',
            name='requires_reregistration',
            field=models.BooleanField(default=False, verbose_name='Требуется повторная регистрация'),
        ),
        migrations.AddField(
            model_name='searchairticket',
            name='transfer_count',
            field=models.PositiveIntegerField(default=0, help_text='0 - прямой рейс, 1 - одна пересадка, 2 - две пересадки', verbose_name='Количество пересадок'),
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
