# Generated by Django 5.2 on 2025-04-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_searchairticket_night_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='populartour',
            name='near_sea',
            field=models.BooleanField(default=False, verbose_name='Рядом с морем'),
        ),
        migrations.AddField(
            model_name='searchtour',
            name='near_sea',
            field=models.BooleanField(default=False, verbose_name='Рядом с морем'),
        ),
    ]
