# Generated by Django 5.2 on 2025-04-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_populartour_near_sea_searchtour_near_sea'),
    ]

    operations = [
        migrations.AddField(
            model_name='populartour',
            name='center_distance',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Расстояние от отеля до центра города в километрах', max_digits=5, null=True, verbose_name='Расстояние до центра (км)'),
        ),
        migrations.AddField(
            model_name='searchtour',
            name='center_distance',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Расстояние от отеля до центра города в километрах', max_digits=5, null=True, verbose_name='Расстояние до центра (км)'),
        ),
    ]
