# Generated by Django 5.2 on 2025-04-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_populartour_center_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populartour',
            name='center_distance',
        ),
        migrations.RemoveField(
            model_name='searchtour',
            name='center_distance',
        ),
    ]
