/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        roboto: "var(--font-roboto)",
      },
      colors: {
        background: "var(--color-background)",
        bg_header: "var(--color-header-background)",
        btn_header: "var(--color-header-button)",
        btn_header_profile: "var(--color-header-button-profile)",
        text_header_profile: "var(--color-header-text-profile)",
        btn_active_header: "var(--color-header-button_active)",
        bg_search: "var(--color-search-background)",
        btn_search_hover: "var(--color-btn-search-background-hover)",
        btn_search: "var(--color-btn-search-background)",
        text_primary: "var(--color-primary-text)",
        text_secondary: "var(--color-secondary-text)",
        text_crossed_out: "var(--color-crossed_out-text)",
        bg_arrow: "var(--color-arrow-button)",
        bg_hot_tickets: "var(--color-hot_tickets-background)",
        bg_footer: "var(--color-footer-background)",
        link_footer: "var(--color-footer-link)",
        text_footer: "var(--color-footer-text)",
        white_black: "var(--color-white-black)",
        text_header_button: "var(--color-header-text-button)",
        bg_menu_mobile: "var(--color-menu-mobile--background)",
        bg_burger_mobile: "var(--color-burger-mobile--background)",
        line_burger_mobile: "var(--color-line-mobile--burger)",
        bg_round_profile: "var(--color-round-profile)",
        bg_burger_pc: "var(--color-background--burger-pc)",
        text_heading: "var(--color-text-heading)",
        bg_input: "var(--color--input)",
        bg_input_button: "var(--color--input-button)",
        bg_auth_left: "var(--color--auth-left)",
        text_auth_mobile: "var(--color--text--auth-mobile)",
        bg_search_passengers: "var(--color--search--passengers)",
        bg_travel_ideas: "var(--color--travel-ideas)",
        bg_arrow_hover: "var(--color-arrow-hover)",
        bg_search_result: "var(--color--search-result)",
        bg_ticket: "var(--color--ticket)",
        bg_ticket_right: "var(--color--ticket-right)",
        bg_ticket_button: "var(--color--ticket-button)",
        stroke_ticket_choise_active: "var(--color--ticket-choise-active)",
        stroke_ticket_choise: "var(--color--ticket-choise)",
        price_ticket: "var(--color--price-ticket)",
        favourites_color: "var(--color--favourites-color)",
        text_sorting_not_active: "var(--color--sorting--not-active)",
        bg_slider_sort: "var(--color--slider--sorting)",
        text_button_show_more: "var(--color--button--show-more)",
      },
    },
  },
  plugins: [],
};
