import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ThemeProvider } from "./context/ThemeContext"; // Импортируем ThemeProvider
import { AuthProvider } from "./context/AuthContext"; // Импортируем AuthProvider
import { usePathname, useSearchParams } from "next/navigation";
import Menu_mobile from "./components/Menu_mobile"; // Кнопка для переключения темы

// Используем шрифт Roboto
const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Компонент Layout
const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider>
          <AuthProvider>
            <Header />
            {children}
            <Footer />
            <Menu_mobile />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default Layout;
